[project]
name = "django-tpl"
dynamic = ["version"]
description = "The Django project template with supporting services containers (e.g. postgresql, smtp etc.)"
requires-python = ">= 3.10"
maintainers = [
    { name = "Serhii Horodilov", email = "shorodilov@devsforge.org" },
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["python", "django", "template", "web", "framework"]
# see also:: https://pypi.org/classifiers
classifiers = [
    "Framework :: Django",
    "Framework :: Django :: 5",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development",
    "Topic :: Software Development :: Version Control :: Git",
]
dependencies = [
    "django>=5.2.7",
    "psycopg[binary]",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "bumpver>=2025.1131",
    "pytest-django>=4.11.1",
]

[tool.bumpver]
current_version = "2026.01rc1"
version_pattern = "YYYY.0M[.PATCH][PYTAGNUM]"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
]

[tool.black]
line-length = 119
target-version = ["py310", "py311", "py312"]
include = "\\.pyi?$"
